name: "CI Assignment - Sona"

on:
  push:
    branches:
      - assignment-06-07-CI-CD-Sona-Arzumanyan

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Print greeting
         run: echo "Hello from Sona's CI/CD pipeline!!!! Nice to see you here!!"

       - name: Print current date and time
         run: date

       - name: Print names of changed files between current and main branch
         run: |
            echo "Changed files compared to main"
            git fetch origin main
            git diff --name-only origin/main HEAD > changed_files.txt
            cat changed_files.txt

            if grep -q "SonaArzumanyan-ci.yml" changed_files.txt; then 
              echo "Success: Workflow file changed!"
            else 
              echo "Failure: Workflow file not changed!"
              exit 1
            fi
